services:
  torrent-search:
    build: .
    container_name: torrent-search
    ports:
      - "3000:3000"
    env_file:
      - .env
как    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
